package feed

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/gorilla/feeds"
	"github.com/skyth3r/monzo-blog-feed/internal/config"
	"github.com/skyth3r/monzo-blog-feed/internal/models"
	"github.com/skyth3r/monzo-blog-feed/internal/utils"
)

func GenerateFeeds(blogItems *[]models.BlogItem, feedName string) error {
	sort.Slice(*blogItems, func(i, j int) bool {
		if (*blogItems)[i].PubDate.After((*blogItems)[j].PubDate) {
			return true
		}
		if (*blogItems)[i].PubDate.Before((*blogItems)[j].PubDate) {
			return false
		}
		return (*blogItems)[i].Link < (*blogItems)[j].Link
	})

	changes, err := generateItemFeed(blogItems, fmt.Sprintf("%s_feed_items", feedName))
	if err != nil {
		return err
	}

	if changes {
		feed, err := convertToFeed(blogItems, feedName)
		if err != nil {
			return err
		}

		err = generateRssFeed(feed, feedName)
		if err != nil {
			return err
		}
		err = generateAtomFeed(feed, feedName)
		if err != nil {
			return err
		}
		err = generateJsonFeed(feed, feedName)
		if err != nil {
			return err
		}
	}

	return nil
}

func generateItemFeed(items *[]models.BlogItem, name string) (bool, error) {
	existingPath := fmt.Sprintf(".json/%s.json", name)
	var existingItems []models.BlogItem
	noChanges := false

	if existingFile, err := os.Open(existingPath); err == nil {
		defer existingFile.Close()
		decoder := json.NewDecoder(existingFile)
		if err := decoder.Decode(&existingItems); err == nil {
			noChanges = true
		}
	}

	if noChanges && reflect.DeepEqual(existingItems, *items) {
		return false, nil
	}

	jsonFile, err := os.Create(fmt.Sprintf("%s.json", name))
	if err != nil {
		return false, err
	}
	defer jsonFile.Close()

	encoder := json.NewEncoder(jsonFile)
	encoder.SetIndent("", "  ")
	err = encoder.Encode(items)
	if err != nil {
		return false, err
	}

	err = utils.MoveFile(fmt.Sprintf("%s.json", name), fmt.Sprintf(".json/%s.json", name))
	if err != nil {
		return false, err
	}

	return true, nil
}

func convertToFeed(items *[]models.BlogItem, name string) (*feeds.Feed, error) {
	title := "Monzo"
	tagName := ""

	parts := strings.Split(name, "_")
	if len(parts) > 1 {
		tagName = parts[len(parts)-1]
		tagName = strings.ToUpper(tagName[:1]) + tagName[1:]
	}

	if tagName != "" {
		title = fmt.Sprintf("Monzo - %s", tagName)
	}

	feed := &feeds.Feed{
		Title:       title,
		Link:        &feeds.Link{Href: config.Root},
		Description: "An unofficial Monzo blog feed generated by Akash Goswami (https://akashgoswami.dev)",
		Created:     time.Now(),
		Image: &feeds.Image{
			Title: "Monzo",
			Link:  config.Root,
			Url:   "https://raw.githubusercontent.com/skyth3r/monzo-blog-feed/refs/heads/main/icon.svg",
		},
	}

	if strings.Contains((*items)[0].Link, "https://monzo.com/us/blog") {
		feed.Title = "Monzo US"
		feed.Link = &feeds.Link{Href: config.UsRoot}
		feed.Description = "An unofficial Monzo US blog feed generated by Akash Goswami (https://akashgoswami.dev)"
		feed.Image.Link = config.UsRoot
	}

	for _, item := range *items {
		feed.Items = append(feed.Items, &feeds.Item{
			Title:       item.Title,
			Link:        &feeds.Link{Href: item.Link},
			Description: item.Description,
			Created:     item.PubDate,
		})
	}

	sort.Slice(feed.Items, func(i, j int) bool {
		return feed.Items[i].Created.After(feed.Items[j].Created)
	})

	return feed, nil
}

func generateRssFeed(feed *feeds.Feed, name string) error {
	rss, err := feed.ToRss()
	if err != nil {
		return err
	}

	rssFile, err := os.Create(fmt.Sprintf("%s.rss", name))
	if err != nil {
		return err
	}
	defer rssFile.Close()

	_, err = rssFile.WriteString(rss)
	if err != nil {
		return err
	}

	err = utils.MoveFile(fmt.Sprintf("%s.rss", name), fmt.Sprintf("feeds/%s.rss", name))
	if err != nil {
		return err
	}

	return nil
}

func generateAtomFeed(feed *feeds.Feed, name string) error {
	atom, err := feed.ToAtom()
	if err != nil {
		return err
	}

	atomFile, err := os.Create(fmt.Sprintf("%s.atom", name))
	if err != nil {
		return err
	}
	defer atomFile.Close()

	_, err = atomFile.WriteString(atom)
	if err != nil {
		return err
	}

	err = utils.MoveFile(fmt.Sprintf("%s.atom", name), fmt.Sprintf("feeds/%s.atom", name))
	if err != nil {
		return err
	}

	return nil
}

func generateJsonFeed(feed *feeds.Feed, name string) error {
	jsonFeed, err := feed.ToJSON()
	if err != nil {
		return err
	}

	jsonFile, err := os.Create(fmt.Sprintf("%s.json", name))
	if err != nil {
		return err
	}
	defer jsonFile.Close()

	_, err = jsonFile.WriteString(jsonFeed)
	if err != nil {
		return err
	}

	err = utils.MoveFile(fmt.Sprintf("%s.json", name), fmt.Sprintf("feeds/%s.json", name))
	if err != nil {
		return err
	}

	return nil
}
